nameoverride: ""

appName: "netedge-proxy"
appInstanceId: "netedge-proxy-12321"

mongo:
  deploy: false
  name: mongo
  image: mongo
  storage: 1Gi
  replicas: 1
  user: "" #bmV0ZWRnZQ==
  password: "" # TUVDXCFtMG5nMA==
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017

mx2:
  name: mx2
  image: uminhonetedge/mx2:1.2.4
  imagePullPolicy: Always
  replicas: 1
  service:
    type: NodePort
    port: 8080
    targetPort: 5001
    nodePort: 30000
  ingress:
    url: mx2.netedge-proxy.com

auth:
  name: auth
  image: uminhonetedge/openid-server:1.0.54
  imagePullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
    
meao:
  name: meao
  image: uminhonetedge/meao:1.0.2
  imagePullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 5002
    targetPort: 5002
  db: meao
  osm:
    hostname: "nbi" # "192.168.86.210"

deviceapp:
  name: deviceapp
  image: uminhonetedge/proxy_client:system
  imagePullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 5005
    targetPort: 5005

userapp:
  name: userapp
  image: uminhonetedge/proxy_client_ui:1.2.10
  imagePullPolicy: Always
  replicas: 1
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30001

mongoexpress: false
  # name: mongoexpress
  # image: mongo-express
  # imagePullPolicy: Always
  # replicas: 1
  # service:
  #   type: NodePort
  #   port: 8081
  #   targetPort: 8081
  #   nodePort: 30001
  # ingress:
  #   url: mongoexpress.netedge-proxy.com

